force-app/main/default/objects/MaintenanceRequest__c/MaintenanceRequest__c.object-meta.xml
<CustomObject>
    <label>Maintenance Request</label>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <nameField>
        <label>Maintenance Request Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MaintenanceRequest__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Required via validation rule.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MaintenanceRequest__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
                <default>true</default>
                <label>Medium</label>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MaintenanceRequest__c/fields/RentalAsset__c.field-meta.xml
<CustomField>
    <fullName>RentalAsset__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rental Asset</label>
    <referenceTo>RentalAsset__c</referenceTo>
    <relationshipLabel>Maintenance Requests</relationshipLabel>
    <relationshipName>MaintenanceRequests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MaintenanceRequest__c/fields/RequestedAt__c.field-meta.xml
<CustomField>
    <fullName>RequestedAt__c</fullName>
    <label>Requested At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MaintenanceRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Owner__c/Owner__c.object-meta.xml
<CustomObject>
    <label>Owner</label>
    <nameField>
        <label>Owner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Owner__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>test</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Owner__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
    <required>true</required>
</CustomField>

force-app/main/default/objects/RentalAsset__c/RentalAsset__c.object-meta.xml
<CustomObject>
    <label>Rental Asset</label>
    <nameField>
        <label>Rental Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rental Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RentalAsset__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Text</type>
    <length>80</length>
    <required>true</required>
</CustomField>

force-app/main/default/objects/RentalAsset__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Owner</label>
    <referenceTo>Owner__c</referenceTo>
    <relationshipLabel>Rental Assets</relationshipLabel>
    <relationshipName>RentalAssets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RentalAsset__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <type>Text</type>
    <length>255</length>
    <required>true</required>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
	public static Account createAccount(Boolean doInsert) {
		return createAccount('testAccount', doInsert);
	}
	
	public static Account createAccount(String name, Boolean doInsert) {
		Account acc = new Account(name = name);
		if(doInsert) {
			insert acc;
		}
		return acc;
	}
	
	public static Contact createContact(Boolean doInsert) {
		Account acc = createAccount(true);
		return createContact(acc.id, true);
	}
	
	public static Contact createContact(Id accountId, Boolean doInsert) {
		Contact c = new Contact(firstName = 'Apex', lastName = 'Hours', accountId = accountId);
		if(doInsert) {
			insert c;
		}
		return c;
	}
	public static List<Opportunity> createOpportunity(Id accountId, Integer numOpps) {
		List<Opportunity> opps = new List<Opportunity>();
		for(Integer i = 1; i <= numOpps; i++) {
			Opportunity opp = new Opportunity();
			opp.name = 'Account ' + i;
			opp.accountId = accountid;
			opp.amount = 100;
			opp.closeDate = Date.today().addDays(5);
			opp.stageName = 'Prospecting';
			opps.add(opp);
		}
		return opps;
	}

  public static User createTestUser() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' LIMIT 1];
        User u = new User(
            Alias = 'maint', Email='maint@test.com', 
            LastName='Testing', ProfileId = p.Id, 
            UserName='maintuser' + DateTime.now().getTime() + '@test.com',
            EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', TimeZoneSidKey='America/Los_Angeles'
        );
        return u;
    }

	public static Owner__c createOwner(Boolean doInsert) {
        Owner__c owner = new Owner__c(
            Name = 'Test Owner',
            Email__c = 'owner@test.com',
            Phone__c = '015208832076'
        );
        if(doInsert) insert owner;
        return owner;
    }

		public static RentalAsset__c createAsset(Id ownerID, Boolean DoInsert){
		RentalAsset__c asset = new RentalAsset__c(
			Name = 'Test Asset',
			Owner__c = ownerID,
			City__c = 'Osnabruck',
			Street__c = 'Wersener Str 46'
		);
		if(DoInsert) insert asset;
		return asset;
	}

    public static List<MaintenanceRequest__c> createRequests(Integer count, String status, Id assetId) {
        List<MaintenanceRequest__c> reqs = new List<MaintenanceRequest__c>();
        for(Integer i=0; i<count; i++) {
            reqs.add(new MaintenanceRequest__c(
                Name = 'Test Req ' + i,
                Status__c = status,
                RentalAsset__c = assetId, 
                Priority__c = 'Medium',
                RequestedAt__c = System.now(),
                Description__c = 'Test Description ' + i
            ));
        }
        return reqs;
    }
}