force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
      <pluralLabel>Invoices</pluralLabel>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoicePdfServiceTest.cls
@IsTest
public class InvoicePdfServiceTest {

    @IsTest
    static void testPdfGeneratedWhenStatusBecomesSent() {

       
        Invoice__c inv = new Invoice__c();
        inv.Name = 'Test Invoice';
        inv.Status__c = 'Draft';
        insert inv;

        
        Integer filesBefore = [
            SELECT COUNT()
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :inv.Id
        ];
        System.assertEquals(0, filesBefore);

        
        inv.Status__c = 'Sent';
        Test.startTest();
        update inv;
        Test.stopTest();

        List<ContentDocumentLink> links = [
            SELECT ContentDocumentId
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :inv.Id
        ];

        System.assertEquals(1,links.size());
    }
}