force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <pluralLabel>Payments</pluralLabel>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/AmountInBase__c.field-meta.xml
<CustomField>
    <fullName>AmountInBase__c</fullName>
    <label>Amount in base</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyCode__c</fullName>
    <label>Currency Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>HUF</fullName>
            </value>
            <value>
                <fullName>KGS</fullName>
            </value>
            <value>
                <fullName>RUB</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/FxError__c.field-meta.xml
<CustomField>
    <fullName>FxError__c</fullName>
    <label>Fx Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/FxLastUpdatedAt__c.field-meta.xml
<CustomField>
    <fullName>FxLastUpdatedAt__c</fullName>
    <label>Fx Last Updated At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/FxRate__c.field-meta.xml
<CustomField>
    <fullName>FxRate__c</fullName>
    <label>Fx Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/FxStatus__c.field-meta.xml
<CustomField>
    <fullName>FxStatus__c</fullName>
    <label>FxStatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RO_CurrencyConfig__mdt/RO_CurrencyConfig__mdt.object-meta.xml
<CustomObject>
    <label>RO Currency Config</label>
    <pluralLabel>RO Currency Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/RO_CurrencyConfig__mdt/fields/BaseCurrency__c.field-meta.xml
<CustomField>
    <fullName>BaseCurrency__c</fullName>
    <label>Base Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentService.cls
public with sharing class PaymentService {

    // recursion guard
    private static Boolean isRunning = false;

    // Fast path - before trigger

    public static void processFastPathBefore(
        List<Payment__c> newList
    ) {
        processFastPathBefore(newList, null);
    }

    public static void processFastPathBefore(
        List<Payment__c> newList,
        Map<Id, Payment__c> oldMap
    ) {
        if(newList == null || newList.isEmpty()) return;

        RO_CurrencyConfig__mdt cfg =
            RO_CurrencyConfig__mdt.getInstance('Default');

        String baseCurrency = cfg.BaseCurrency__c;

        for(Payment__c p : newList) {

            if(p.Amount__c == null || p.CurrencyCode__c == null)
                continue;

            Boolean amountChanged =
                oldMap == null ||
                p.Amount__c != oldMap.get(p.Id)?.Amount__c;

            Boolean currencyChanged =
                oldMap == null ||
                p.CurrencyCode__c != oldMap.get(p.Id)?.CurrencyCode__c;

            if(String.valueOf(p.CurrencyCode__c) == baseCurrency &&
            (amountChanged || currencyChanged || p.FxRate__c == null)) {

                p.FxRate__c = 1;
                p.AmountInBase__c = p.Amount__c;
                p.FxStatus__c = 'Success';
                p.FxLastUpdatedAt__c = System.now();
                p.FxError__c = null;
            }
        }
    }


// After trigger - enqueue future 

    public static void processFxUpdates(
        Map<Id, Payment__c> oldMap,
        Map<Id, Payment__c> newMap
    ) {
        if(isRunning) return;
        isRunning = true;

        try {

            if(newMap == null || newMap.isEmpty()) return;

            RO_CurrencyConfig__mdt cfg =
                RO_CurrencyConfig__mdt.getInstance('Default');

            String baseCurrency = cfg.BaseCurrency__c;

            Set<Id> toUpdateFuture = new Set<Id>();

            for(Payment__c p : newMap.values()) {

                if(p.Amount__c == null || p.CurrencyCode__c == null)
                    continue;

                Boolean amountChanged =
                    oldMap == null ||
                    p.Amount__c != oldMap.get(p.Id)?.Amount__c;

                Boolean currencyChanged =
                    oldMap == null ||
                    p.CurrencyCode__c != oldMap.get(p.Id)?.CurrencyCode__c;

                Boolean needsFx =
                p.CurrencyCode__c != baseCurrency &&
                (
                p.FxRate__c == null ||
                p.AmountInBase__c == null ||
                amountChanged ||
                currencyChanged
    );

if(needsFx) {
    toUpdateFuture.add(p.Id);
}}

        if(!toUpdateFuture.isEmpty()
            && !System.isFuture()
            && !System.isBatch()
            && !System.isQueueable()) {
        RO_FxFuture.updatePayments(toUpdateFuture);
        }

        }finally {
            isRunning = false;
        }
    }
    }